spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  server:
    port: 8443
    protocol: protocol="org.apache.coyote.http11.Http11Protocol"
    maxThreads: 150
    SSLEnabled: true
    scheme: https
    secure: true
    keystoreFile: C:/cert/keystore
    keystorePass: 8406
    clientAuth: false
    sslProtocol: TLS
